import type { OrgGroupNode } from './Organogram.types'

/** Dados de demonstração alinhados ao mockup (Desenvolvimento + Marketing). */
export const ORGANOGRAM_DEMO_ROOTS: OrgGroupNode[] = [
  {
    kind: 'group',
    id: 'desenvolvimento',
    title: 'DESENVOLVIMENTO',
    accent: '#fbbf24',
    countLabel: '3 Subgrupos',
    cost: { display: 'R$ 120.000', deltaPct: 25 },
    hours: { display: '120h', deltaPct: 12 },
    costPositive: true,
    hoursPositive: false,
    defaultExpanded: true,
    children: [
      {
        kind: 'group',
        id: 'frontend',
        title: 'Front End',
        accent: '#fbbf24',
        countLabel: '2 Colaboradores',
        cost: { display: 'R$ 40.000', deltaPct: 8 },
        hours: { display: '40h', deltaPct: 3 },
        costPositive: true,
        hoursPositive: false,
        defaultExpanded: true,
        children: [
          {
            kind: 'person',
            id: 'p-gf',
            name: 'Guilherme F.',
            role: 'Tech Lead',
            costLabel: 'R$ 20.000',
            hoursLabel: '40h',
            initials: 'GF',
          },
          {
            kind: 'person',
            id: 'p-lb',
            name: 'Lucas B.',
            role: 'Tech Lead',
            costLabel: 'R$ 20.000',
            hoursLabel: '40h',
            initials: 'LB',
          },
        ],
      },
      {
        kind: 'group',
        id: 'backend',
        title: 'Back End',
        accent: '#fbbf24',
        countLabel: '2 Colaboradores',
        cost: { display: 'R$ 35.000', deltaPct: 5 },
        hours: { display: '35h', deltaPct: 2 },
        costPositive: true,
        hoursPositive: true,
        defaultExpanded: false,
        children: [],
      },
      {
        kind: 'group',
        id: 'dados',
        title: 'Dados',
        accent: '#fbbf24',
        countLabel: '2 Colaboradores',
        cost: { display: 'R$ 45.000', deltaPct: 12 },
        hours: { display: '45h', deltaPct: 6 },
        costPositive: true,
        hoursPositive: false,
        defaultExpanded: true,
        children: [
          {
            kind: 'person',
            id: 'p-jc',
            name: 'Jhonatan C.',
            role: 'Tech Lead',
            costLabel: 'R$ 22.500',
            hoursLabel: '40h',
            initials: 'JC',
          },
          {
            kind: 'person',
            id: 'p-bf',
            name: 'Bruno F.',
            role: 'Tech Lead',
            costLabel: 'R$ 22.500',
            hoursLabel: '40h',
            initials: 'BF',
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'marketing',
    title: 'MARKETING',
    accent: '#22d3ee',
    countLabel: '2 Subgrupos',
    cost: { display: 'R$ 85.000', deltaPct: 15 },
    hours: { display: '90h', deltaPct: 8 },
    costPositive: true,
    hoursPositive: true,
    defaultExpanded: false,
    children: [],
  },
]
